In [2]:
import pandas as pd
from sklearn.naive_bayes import BernoulliNB

In [3]:
data={
    "WIN":[1,1,1,0,1,0,0,1],
"PRICE":[0,1,0,1,1,0,0,1],
    "Class":['spam','spam','Notspam','spam','notspam','notspam','spam','spam']
}

In [4]:
df=pd.DataFrame(data)
df

   WIN  PRICE    Class
0    1      0     spam
1    1      1     spam
2    1      0  Notspam
3    0      1     spam
4    1      1  notspam
5    0      0  notspam
6    0      0     spam
7    1      1     spam

In [5]:
X=df[["WIN","PRIZE"]]

KeyError: "['PRIZE'] not in index"

In [7]:
import warnings
warnings.filterwarnings('ignore')
prediction=model.predict([[1,1]])
print("My model Result:",prediction)

NameError: name 'model' is not defined

Multinomial NB

In [7]:
from sklearn.naive_bayes import MultinomialNB
mails=[
    "win money now",
    "limited offer win prize",
    "Attend classes regularly",
    "you won the lottery",
    "will meet in tommarow",
    "you are shortlisted for next round",
    "Pay money to get into the company",
    "please confirm your email adress"]
labels=[0,0,1,0,1,1,0,1]

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
vector=CountVectorizer()
X=vector.fit_transform(mails)
print(X)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 29 stored elements and shape (7, 27)>
  Coords	Values
  (0, 23)	1
  (0, 11)	1
  (0, 13)	1
  (1, 23)	1
  (1, 8)	1
  (1, 14)	1
  (1, 16)	1
  (2, 2)	1
  (2, 3)	1
  (2, 17)	1
  (3, 25)	1
  (3, 24)	1
  (3, 20)	1
  (3, 9)	1
  (4, 22)	1
  (4, 10)	1
  (4, 7)	1
  (4, 21)	1
  (5, 25)	1
  (5, 1)	1
  (5, 19)	1
  (5, 6)	1
  (5, 12)	1
  (5, 18)	1
  (6, 15)	1
  (6, 4)	1
  (6, 26)	1
  (6, 5)	1
  (6, 0)	1

In [ ]:
df=pd.DataFrame(
    X.toarray(),
    columns=

In [11]:
from sklearn.naive_bayes import GaussianNB
data={
    "Height":[170,160,168],
    "Weight":[65,55,62],
    "Class":['Fit','Fit','Fit']}

In [12]:
df=pd.DataFrame(data)
df

   Height  Weight Class
0     170      65   Fit
1     160      55   Fit
2     168      62   Fit

In [13]:
X=[["Weight","Height"]]
Y=["Class"]

In [61]:
import numpy as np
import pandas  as pd
from sklearn.model_selection import train_test_split

In [62]:
df=pd.read_csv("mail_data.csv")
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [63]:
df.shape

(5572, 2)

In [64]:
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS
print(ENGLISH_STOP_WORDS)
print(len(ENGLISH_STOP_WORDS))

frozenset({'nothing', 'hasnt', 'these', 'am', 'latterly', 'thick', 'themselves', 'my', 'etc', 'mostly', 'eight', 'anyway', 'otherwise', 'almost', 'against', 'him', 'can', 'nobody', 'nowhere', 'first', 'who', 'whose', 'thereafter', 'thereby', 'sometime', 'should', 'once', 'nevertheless', 'ten', 'or', 'eleven', 'fire', 'an', 'because', 'yourself', 'de', 'whoever', 'whom', 'side', 'before', 'a', 'move', 'below', 'until', 'there', 'same', 'often', 'for', 'might', 'any', 'somewhere', 'without', 'each', 'together', 'moreover', 'none', 'cant', 'whole', 'never', 'amount', 'within', 'please', 'twenty', 'last', 'mine', 'hundred', 'they', 'more', 'sincere', 'whereas', 'whatever', 'bottom', 'wherein', 'even', 'across', 'couldnt', 'that', 'this', 'its', 'afterwards', 'being', 'yourselves', 'interest', 'whenever', 'had', 're', 'myself', 'give', 'ever', 'himself', 'upon', 'found', 'he', 'beforehand', 'few', 'me', 'everything', 'five', 'former', 'hers', 'of', 'else', 'among', 'forty', 'seems', 'system', 'un', 'with', 'hereafter', 'several', 'noone', 'than', 'the', 'will', 'here', 'what', 'many', 'enough', 'nine', 'anyhow', 'describe', 'co', 'therefore', 'name', 'over', 'beside', 'full', 'every', 'cry', 'always', 'about', 'towards', 'per', 'everywhere', 'has', 'how', 'become', 'neither', 'amoungst', 'whereafter', 'bill', 'while', 'were', 'mill', 'hereupon', 'behind', 'her', 'namely', 'seem', 'during', 'due', 'keep', 'well', 'thus', 'other', 'either', 'sixty', 'hereby', 'through', 'find', 'thru', 'around', 'six', 'after', 'cannot', 'and', 'those', 'was', 'therein', 'seemed', 'least', 'if', 'along', 'on', 'why', 'top', 'when', 'third', 'some', 'part', 'us', 'out', 'at', 'to', 'yours', 'now', 'take', 'are', 'though', 'their', 'own', 'whereupon', 'something', 'then', 'wherever', 'between', 'put', 'although', 'empty', 'them', 'perhaps', 'is', 'throughout', 'however', 'already', 'go', 'could', 'most', 'also', 'back', 'still', 'but', 'it', 'get', 'others', 'which', 'somehow', 'yet', 'elsewhere', 'twelve', 'onto', 'sometimes', 'done', 'whereby', 'everyone', 'fill', 'she', 'except', 'toward', 'above', 'ltd', 'call', 'detail', 'up', 'con', 'may', 'alone', 'off', 'anyone', 'someone', 'whether', 'we', 'hence', 'ours', 'three', 'made', 'be', 'into', 'whence', 'your', 'such', 'besides', 'his', 'seeming', 'anywhere', 'as', 'fifteen', 'whither', 'becomes', 'so', 'see', 'would', 'beyond', 'all', 'became', 'not', 'itself', 'much', 'again', 'inc', 'you', 'another', 'our', 'rather', 'down', 'two', 'under', 'ie', 'only', 'have', 'in', 'thin', 'since', 'formerly', 'herself', 'via', 'do', 'fifty', 'nor', 'front', 'becoming', 'very', 'from', 'meanwhile', 'herein', 'one', 'further', 'no', 'must', 'i', 'indeed', 'been', 'too', 'by', 'four', 'anything', 'latter', 'amongst', 'eg', 'where', 'ourselves', 'thereupon', 'less', 'both', 'next', 'serious', 'thence', 'show'})
318

In [65]:
from sklearn.feature_extraction.text import TfidfVectorizer
text=["This is a free offer for today so hurryup!"]
vector=TfidfVectorizer(stop_words='english')
X=vector.fit_transform(text)
print(vector.get_feature_names_out())

['free' 'hurryup' 'offer' 'today']

In [66]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4 stored elements and shape (1, 4)>
  Coords	Values
  (0, 0)	0.5
  (0, 2)	0.5
  (0, 3)	0.5
  (0, 1)	0.5

In [67]:
#Encoding proocess
from sklearn.preprocessing import LabelEncoder
df['Category']

0        ham
1        ham
2       spam
3        ham
4        ham
        ...
5567    spam
5568     ham
5569     ham
5570     ham
5571     ham
Name: Category, Length: 5572, dtype: object

In [68]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Category']=le.fit_transform(df['Category'])

In [69]:
X=df['Message']
Y=df['Category']

In [70]:
X.head()

0    Go until jurong point, crazy.. Available only ...
1                        Ok lar... Joking wif u oni...
2    Free entry in 2 a wkly comp to win FA Cup fina...
3    U dun say so early hor... U c already then say...
4    Nah I don't think he goes to usf, he lives aro...
Name: Message, dtype: object

In [71]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=3)

In [72]:
X.shape,X_train.shape,X_test.shape

((5572,), (4457,), (1115,))

In [73]:
Y.shape,y_train.shape,y_test.shape

((5572,), (4457,), (1115,))

In [74]:
print(X_train.head(2))

3075                  Don know. I did't msg him recently.
1787    Do you know why god created gap between your f...
Name: Message, dtype: object

In [75]:
print(y_train.head(2))

3075    0
1787    0
Name: Category, dtype: int64

In [76]:
from sklearn.feature_extraction.text import TfidfVectorizer
vector=TfidfVectorizer(stop_words='english')
X=vector.fit_transform(text)
print(vector.get_feature_names_out())

['free' 'hurryup' 'offer' 'today']

In [77]:
from sklearn.feature_extraction.text import TfidfVectorizer
vector=TfidfVectorizer(stop_words='english',lowercase=True)
X_train_features=vector.fit_transform(X_train)

In [78]:
X_test_features=vector.transform(X_test)
print(X_test_features)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 7687 stored elements and shape (1115, 7431)>
  Coords	Values
  (0, 1)	0.2381316303003606
  (0, 9)	0.2852706805264544
  (0, 14)	0.26797874471323896
  (0, 20)	0.30668032384591537
  (0, 306)	0.23975986557206702
  (0, 405)	0.2381316303003606
  (0, 1041)	0.28016206931555726
  (0, 1082)	0.2451068436245027
  (0, 1361)	0.25132445289897426
  (0, 1405)	0.3176863938914351
  (0, 1549)	0.2646498848307188
  (0, 4386)	0.18353336340308998
  (0, 5213)	0.1988547357502182
  (0, 5373)	0.2365698724638063
  (0, 6920)	0.20571591693537986
  (0, 7271)	0.1940327008179069
  (1, 3491)	0.496093956101028
  (1, 4418)	0.3457696891316818
  (1, 4729)	0.22965776503163893
  (1, 6214)	0.3621564482127515
  (1, 6507)	0.26731535902873493
  (1, 6588)	0.3298937975962767
  (1, 6732)	0.42473488678029325
  (1, 7368)	0.29957800964520975
  (2, 201)	0.2824102268489399
  :	:
  (1110, 6591)	0.7327660015422193
  (1111, 2440)	0.4137350055985486
  (1111, 3227)	0.44384935772735523
  (1111, 6033)	0.4714849709283488
  (1111, 6787)	0.40050175714278885
  (1111, 7353)	0.4991205841293424
  (1112, 1109)	0.35334496762883244
  (1112, 1683)	0.4017087436272034
  (1112, 2329)	0.241856898377491
  (1112, 4170)	0.3307835623173863
  (1112, 5056)	0.2559183043595413
  (1112, 5695)	0.3381604952481646
  (1112, 5778)	0.22807428098549426
  (1112, 6297)	0.3056896872268727
  (1112, 6777)	0.32853717524096393
  (1112, 7071)	0.33558524648843113
  (1113, 2224)	0.33379592674353104
  (1113, 2852)	0.5956422931588335
  (1113, 3113)	0.3384083342515567
  (1113, 3281)	0.3323250860171953
  (1113, 3811)	0.2810308058655509
  (1113, 4038)	0.370235205294137
  (1113, 4080)	0.30459473619554067
  (1114, 4033)	0.8543942045002639
  (1114, 4557)	0.5196253874825217

In [79]:
X_test_features=vector.transform(X_test)
#print(X_test_features)
x_test=pd.DataFrame(
    X_train_features.toarray(),
    columns=vector.get_feature_names_out()
)
print(x_test.head())

    00  000  000pes  008704050406  0089  0121  01223585236  01223585334  \
0  0.0  0.0     0.0           0.0   0.0   0.0          0.0          0.0
1  0.0  0.0     0.0           0.0   0.0   0.0          0.0          0.0
2  0.0  0.0     0.0           0.0   0.0   0.0          0.0          0.0
3  0.0  0.0     0.0           0.0   0.0   0.0          0.0          0.0
4  0.0  0.0     0.0           0.0   0.0   0.0          0.0          0.0

   0125698789   02  ...  zeros  zindgi  zoe  zogtorius  zoom  zouk  zyada  \
0         0.0  0.0  ...    0.0     0.0  0.0        0.0   0.0   0.0    0.0
1         0.0  0.0  ...    0.0     0.0  0.0        0.0   0.0   0.0    0.0
2         0.0  0.0  ...    0.0     0.0  0.0        0.0   0.0   0.0    0.0
3         0.0  0.0  ...    0.0     0.0  0.0        0.0   0.0   0.0    0.0
4         0.0  0.0  ...    0.0     0.0  0.0        0.0   0.0   0.0    0.0

    èn   ú1  〨ud
0  0.0  0.0  0.0
1  0.0  0.0  0.0
2  0.0  0.0  0.0
3  0.0  0.0  0.0
4  0.0  0.0  0.0

[5 rows x 7431 columns]

In [80]:
from sklearn.linear_model import LogisticRegression
Lr=LogisticRegression()
Lr.fit(X_train_features,y_train)

LogisticRegression()

In [84]:
from sklearn.metrics import accuracy_score
model_results = Lr.predict(X_test_features)
model_results

array([1, 0, 0, ..., 0, 0, 0])

In [85]:
from sklearn.metrics import accuracy_score
training_data = Lr.predict(X_train_features)
training_data

array([0, 0, 0, ..., 0, 0, 1])

In [86]:
training_acc=accuracy_score(training_data,y_train)
print("Training Accuracy of model:",training_acc)

Training Accuracy of model: 0.9676912721561588

In [87]:
from sklearn.metrics import accuracy_score
test_data_res= Lr.predict(X_test_features)
test_data_res

array([1, 0, 0, ..., 0, 0, 0])

In [88]:
testing_acc=accuracy_score(test_data_res,y_test)
print("Training Accuracy of model:",testing_acc)

Training Accuracy of model: 0.9668161434977578

In [1]:
import pandas as pd
df=pd.read_csv("play_tennis.csv")
df

     Outlook Temperature Humidity   Wind PlayTennis
0      Sunny         Hot     High   True         No
1      Sunny         Hot     High  False         No
2   Overcast         Hot     High   True        Yes
3       Rain        Mild     High   True        Yes
4       Rain        Cool   Normal   True        Yes
5       Rain        Cool   Normal  False         No
6   Overcast        Cool   Normal  False        Yes
7      Sunny        Mild     High   True         No
8      Sunny        Cool   Normal   True        Yes
9       Rain        Mild   Normal   True        Yes
10     Sunny        Mild   Normal  False        Yes
11  Overcast        Mild     High  False        Yes
12  Overcast         Hot   Normal   True        Yes
13      Rain        Mild     High  False         No

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split

In [3]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(criterion='entropy')
dt.fit(x_train,y_train)

NameError: name 'x_train' is not defined

In [ ]:
y_pred=dt.predict(x_test)
y_pred

HEART DATASET

In [7]:
df=pd.read_csv("heart.csv")
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [5]:
df.shape

(1025, 14)

In [9]:
df['target'].value_counts()

target
1    526
0    499
Name: count, dtype: int64

In [11]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [12]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df=df.apply(le.fit_transform)
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,18,1,0,18,43,0,1,67,0,10,2,2,3,0
1,19,1,0,28,34,1,0,54,1,29,0,0,3,0
2,36,1,0,31,12,0,1,25,1,25,0,0,3,0
3,27,1,0,33,34,0,1,60,0,0,2,1,3,0
4,28,0,0,27,116,1,1,9,0,18,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,25,1,1,28,52,0,1,63,1,0,2,0,2,1
1021,26,1,0,18,87,0,0,40,1,26,1,1,3,0
1022,13,1,0,8,103,0,0,19,1,10,1,1,2,0
1023,16,0,0,8,83,0,0,58,0,0,2,0,2,1
1024,20,1,0,14,24,0,1,14,0,14,1,1,3,0

In [14]:
x=df.drop('target',axis=1)
y=df['target']

In [15]:
df.head(2)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,18,1,0,18,43,0,1,67,0,10,2,2,3,0
1,19,1,0,28,34,1,0,54,1,29,0,0,3,0

In [16]:
df.tail(2)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
1023,16,0,0,8,83,0,0,58,0,0,2,0,2,1
1024,20,1,0,14,24,0,1,14,0,14,1,1,3,0

In [17]:
import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [18]:
print(sns.get_dataset_names())
df=sns.load_dataset('iris')
df.head(2)

['anagrams', 'anscombe', 'attention', 'brain_networks', 'car_crashes', 'diamonds', 'dots', 'dowjones', 'exercise', 'flights', 'fmri', 'geyser', 'glue', 'healthexp', 'iris', 'mpg', 'penguins', 'planets', 'seaice', 'taxis', 'tips', 'titanic']

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa